### PR TITLE
Create README.de.md

### PR DESCRIPTION
**Pull request by waik**
German translation of README.en.md. On line 18, 21 'GGD' is being mentioned but nowhere in the document. Can someone elaborate on the acronym so I can reference.

### CODE REVIEW

**Comment by bramd** [comment]
It means "Gemeentelijke gezondheidsdienst", a national public health institute in The Netherlands.

**Comment by ryanbnl** [comment]
Local Health Authority, I think that the acronym GGD is important to include because it's used absolutely everywhere.

**Comment by jorisleker** [comment]
Please see issue #24 for proposed folder structure for translations.

**Comment by ryanbnl** [comment]
That's merged now; can you move the file to /translations/de-DE/readme.md please Sebastian? :)

**Comment by waik** [comment]
Added additional translations to the translated folder. I kept the file names in line with the English structure but the de-tag.

**Comment by ryanbnl** [comment]
Wow awesome!

**Pull request merged**
